import { CareerCard, CardStatus, CardType, AgentType, Priority } from './types';

export const MOCK_CARDS: CareerCard[] = [
  {
    id: '1',
    type: CardType.JOB,
    title: 'Senior AI Engineer - Cloud Infrastructure',
    description: 'Vaga detectada no LinkedIn. Enfoque em arquitetura de agentes e implantação em grande escala.',
    origin: 'LinkedIn',
    agentId: AgentType.RADAR,
    status: CardStatus.INBOX,
    priority: Priority.HIGH,
    score: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
    metadata: {
      externalLink: 'https://linkedin.com/jobs/123'
    }
  },
  {
    id: '2',
    type: CardType.POST,
    title: 'Post: A Era da Orquestração de Agentes',
    description: 'Postagem estratégica sugerida para aumentar autoridade técnica em Cloud/IA.',
    agentId: AgentType.CONTENT,
    status: CardStatus.WAITING_APPROVAL,
    priority: Priority.MEDIUM,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: true,
  },
  {
    id: '3',
    type: CardType.MESSAGE,
    title: 'Resposta: Recrutadora da OpenAI',
    description: 'Resposta sugerida para mensagem direta sobre oportunidade de consultoria.',
    agentId: AgentType.INTERVIEW,
    status: CardStatus.WAITING_APPROVAL,
    priority: Priority.CRITICAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: true,
  },
  {
    id: '4',
    type: CardType.PROJECT,
    title: 'Orquestrador MCP - Portfolio MVP',
    description: 'Projeto de portfólio para demonstrar integração entre agentes e ferramentas externas.',
    origin: 'GitHub Ideas',
    agentId: AgentType.PORTFOLIO,
    status: CardStatus.RESUME_REVISION,
    priority: Priority.HIGH,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '5',
    type: CardType.INTERVIEW,
    title: 'Preparo: Entrevista Técnica na Vercel',
    description: 'Simulação gerada pelo agente de entrevistas focada em React & Edge Computing.',
    agentId: AgentType.INTERVIEW,
    status: CardStatus.TRIAGEM,
    priority: Priority.HIGH,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '6',
    type: CardType.JOB,
    title: 'Staff Platform Engineer',
    description: 'Aplicação sugerida com base no score de relevância e histórico de consultoria.',
    origin: 'Vercel Careers',
    agentId: AgentType.RADAR,
    status: CardStatus.APPLICATION,
    priority: Priority.MEDIUM,
    score: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '7',
    type: CardType.INTERVIEW,
    title: 'Recrutamento Google - 1a Fase',
    description: 'Entrevista de triagem com recrutador sobre experiência em Distribuited Systems.',
    agentId: AgentType.INTERVIEW,
    status: CardStatus.SCHEDULED,
    priority: Priority.CRITICAL,
    deadline: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 2).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '8',
    type: CardType.INTERVIEW,
    title: 'Simulação: System Design (Agente)',
    description: 'Sessão de treinamento com o Agente de Entrevistas focada em escalabilidade vertical.',
    agentId: AgentType.INTERVIEW,
    status: CardStatus.TRIAGEM,
    priority: Priority.MEDIUM,
    deadline: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 5).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '9',
    type: CardType.INTERVIEW,
    title: 'Entrevista Final - Startup Unicórnio',
    description: 'Conversa final com CTO sobre cultura e roadmap de produto.',
    agentId: AgentType.INTERVIEW,
    status: CardStatus.SCHEDULED,
    priority: Priority.HIGH,
    deadline: new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() - 1).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '10',
    type: CardType.MESSAGE,
    title: 'Conexão: Senior Manager na Meta',
    description: 'Solicitação de conexão personalizada baseada em interesses comuns em infraestrutura.',
    agentId: AgentType.NETWORKING,
    status: CardStatus.INBOX,
    priority: Priority.MEDIUM,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  },
  {
    id: '11',
    type: CardType.MESSAGE,
    title: 'Follow-up: Networking Dinner NYC',
    description: 'Agradecimento e proposta de call para contato conhecido no evento de networking.',
    agentId: AgentType.NETWORKING,
    status: CardStatus.WAITING_APPROVAL,
    priority: Priority.HIGH,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: true,
  },
  {
    id: '12',
    type: CardType.MESSAGE,
    title: 'Intro: CTO Startup Alvo',
    description: 'Pedido de introdução via contato em comum para sondagem de cultura.',
    agentId: AgentType.NETWORKING,
    status: CardStatus.SENT,
    priority: Priority.HIGH,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    needsApproval: false,
  }
];
